whole:
    time: 1s
    memory: 512MB
    name: marble
    std: std
subtask:
    id: 0
    score: 10
    program:
        testNum: 3
        name: subtask0_rand
    program:
        testNum: 1
        name: subtask0_hack
